name: Build for Production

on:
  workflow_dispatch:

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build packages and apps
        run: yarn build
        env:
          BUILD_ENV: PRODUCTION
          NOCO_API_URL: ${{ secrets.NOCO_API_URL }}
          NOCO_AUTH_TOKEN: ${{ secrets.NOCO_AUTH_TOKEN }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
          retention-days: 1
